"""Add MasterPortfolio and Intervention metrics

Revision ID: d9c50a76901b
Revises: c0f211c82d9a
Create Date: 2026-02-11 19:16:14.727603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9c50a76901b'
down_revision: Union[str, Sequence[str], None] = 'c0f211c82d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practitioner_id', sa.Integer(), nullable=True),
    sa.Column('public_slug', sa.String(), nullable=True),
    sa.Column('total_interventions', sa.Integer(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('total_cost_saved', sa.Float(), nullable=True),
    sa.Column('total_productivity_gain', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practitioner_id')
    )
    op.create_index(op.f('ix_master_portfolios_id'), 'master_portfolios', ['id'], unique=False)
    op.create_index(op.f('ix_master_portfolios_public_slug'), 'master_portfolios', ['public_slug'], unique=True)
    op.add_column('interventions', sa.Column('cost_saved', sa.Float(), nullable=True))
    op.add_column('interventions', sa.Column('productivity_gain', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interventions', 'productivity_gain')
    op.drop_column('interventions', 'cost_saved')
    op.drop_index(op.f('ix_master_portfolios_public_slug'), table_name='master_portfolios')
    op.drop_index(op.f('ix_master_portfolios_id'), table_name='master_portfolios')
    op.drop_table('master_portfolios')
    # ### end Alembic commands ###
