"""Replace evidence_files with evidence_links

Revision ID: e8a9dd8fb1de
Revises: d8b34a088a22
Create Date: 2026-02-11 17:30:15.176167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8a9dd8fb1de'
down_revision: Union[str, Sequence[str], None] = 'd8b34a088a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('evidence_links', sa.JSON(), nullable=True))
    op.drop_column('submissions', 'evidence_files')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('evidence_files', sa.TEXT(), nullable=True))
    op.drop_column('submissions', 'evidence_links')
    # ### end Alembic commands ###
